2025-07-05 22:27:44,275 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:27:44,281 - WARNING - Bad Request: /
2025-07-05 22:27:44,344 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:27:44,346 - WARNING - Bad Request: /favicon.ico
2025-07-05 22:27:51,994 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:27:51,995 - WARNING - Bad Request: /
2025-07-05 22:27:52,012 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:27:52,013 - WARNING - Bad Request: /favicon.ico
2025-07-05 22:30:27,433 - ERROR - Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:30:27,435 - WARNING - Bad Request: /
2025-07-05 22:30:27,481 - ERROR - Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:30:27,483 - WARNING - Bad Request: /favicon.ico
2025-07-05 22:37:42,552 - INFO - /home/steve/Templates/django/test_project/settings.py changed, reloading.
2025-07-05 22:38:06,676 - ERROR - Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:38:06,680 - WARNING - Bad Request: /
2025-07-05 22:38:06,710 - ERROR - Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:38:06,711 - WARNING - Bad Request: /favicon.ico
2025-07-05 22:39:31,137 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:39:31,140 - WARNING - Bad Request: /
2025-07-05 22:39:31,185 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:39:31,187 - WARNING - Bad Request: /favicon.ico
2025-07-05 22:57:55,265 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:57:55,295 - WARNING - Bad Request: /
2025-07-05 22:57:55,499 - ERROR - Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/steve/.local/share/virtualenvs/django-8UlHE-8o/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-07-05 22:57:55,524 - WARNING - Bad Request: /favicon.ico
2025-07-05 22:58:55,840 - INFO - /home/steve/Templates/django/test_project/settings.py changed, reloading.
